namespace BDFM.Domain.Enums
{
    public enum TableNames
    {
        Attachments = 1,
        Correspondences = 2,
        ExternalEntities = 3,
        MailFiles = 4,
        OrganizationalUnits = 5,
        Users = 6,
        AuditLogs = 7,
        Delegations = 8,
        Permissions = 9,
        Roles = 10,
        RolePermissions = 11,
        UnitPermissions = 12,
        UserRoles = 13,
        BusinessRules = 14,
        RuleConditions = 15,
        RuleActions = 16,
        AdvancedAlertRules = 17,
        AdvancedAlertTriggerLogs = 18,
        AutomationExecutionLogs = 19,
        AutomationStepExecutionLogs = 20,
        CustomWorkflows = 21,
        CustomWorkflowSteps = 22,
        CorrespondenceTemplates = 23,
        IntegrationActivityLogs = 24,
        SystemIntegrationSettings = 25,
        Notifications = 26,
        PermittedExternalEntityCommunications = 27,
        DraftVersions = 28,
        RelatedPriorities = 29,
        WorkflowSteps = 30,
        WorkflowStepInteractions = 31,
        WorkflowStepSecondaryRecipients = 32,
        CorrespondenceComment = 33,
        Tags = 34,
        CorrespondenceTags = 35,
        SystemTagTemplates = 36,
    }
}
