### Variables
@baseUrl = http://localhost:5000
@conversationId = 69334c406d6241e69ee49f3c
@userId = 42212628-cddd-4d28-972f-8336492a9d99
@username = saad alsaree
@userLogin = 101313
@fullName = saad alsaree
@email = saad@mail.com
@organizationalUnitId = a2e50645-97cb-41cf-8d23-6b669aea3bc6

### Get Models - جلب قائمة الموديلات المتاحة
GET {{baseUrl}}/api/ollama/models?id={{userId}}&username={{username}}&userLogin={{userLogin}}&fullName={{fullName}}&email={{email}}&organizationalUnitId={{organizationalUnitId}}

